[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
node_bundler = "esbuild"
external_node_modules = [
  "pdf-parse",
  "mammoth",
  "p-limit",
  "@ffmpeg-installer/ffmpeg",
  "@ffprobe-installer/ffprobe"
]